version: "3.3"

services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - ~/.docker/cli-password-manager/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: secretsdb
    ports:
     - 5432:5432
